### ISSUE TITLE
[1.7] OutOfMemory on registerEvents

### ISSUE THREAD

**Issue by MeGysssTaa** [MeGysssTaa/ReflexIssueTracker#101]
```java
[13:36:55 WARN]: Exception in thread "Craft Scheduler Thread - 5"
[13:36:55 WARN]: org.apache.commons.lang.UnhandledException: Plugin Reflex v10.1-1U generated an exception while executing task 13
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at java.util.HashMap.resize(Unknown Source)
        at java.util.HashMap.putVal(Unknown Source)
        at java.util.HashMap.put(Unknown Source)
        at java.util.HashSet.add(Unknown Source)
        at org.bukkit.plugin.java.JavaPluginLoader.createRegisteredListeners(JavaPluginLoader.java:242)
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:534)
        at rip.reflex.Kc.<init>(on:174)
        at rip.reflex.Reflex.log(gn:474)
        at rip.reflex.Reflex$$Lambda$10/1057937925.run(Unknown Source)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

**Comment by bob7l** [comment]
Still not fixed: 

`[09:02:22] [Craft Scheduler Thread - 3/INFO]: (Reflex/INFO) | Loading theme 'ModernBlue_EN'
[09:02:22] [Craft Scheduler Thread - 3/INFO]: (Reflex/INFO) | Using theme ModernBlue_EN
[09:02:22] [Craft Scheduler Thread - 3/INFO]: (Reflex/INFO) | Selected theme: 'ModernBlue_EN' by 'Reflex Development Team (DarksideCode)'
[09:02:22] [Craft Scheduler Thread - 3/INFO]: (Reflex/INFO) | Loading Reflex 10.5-1U (J1.8.0_91S1.7.XA2)
[09:02:25] [Craft Scheduler Thread - 3/WARN]: Exception in thread "Craft Scheduler Thread - 3" 
[09:02:25] [Craft Scheduler Thread - 3/WARN]: org.apache.commons.lang.UnhandledException: Plugin Reflex v10.5-1U generated an exception while executing task 9
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.resize(HashMap.java:703)
	at java.util.HashMap.putVal(HashMap.java:662)
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)
	at org.bukkit.plugin.java.JavaPluginLoader.createRegisteredListeners(JavaPluginLoader.java:242)
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:534)
	at rip.reflex.Reflex.getBanInfo(cl:271)
	at rip.reflex.Reflex$$Lambda$17/982069540.run(Unknown Source)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more`
