### ISSUE TITLE
I'm using the lastest version but it have an error.

### ISSUE THREAD

**Issue by CraftG** [MeGysssTaa/ReflexIssueTracker#117]
Hello!
(I am Chinese, English is not good, I use the translation, please excuse me.)
I bought your anti-cheating a few days ago but I found the error without changing any configuration files!
Within the server, the player can't move!
The error message is as follows:
[23:10:53 WARN]: [Reflex] Plugin Reflex v10.1-2U generated an exception while executing task 33
java.lang.RuntimeException: Sync check error
        at rip.reflex.Fb.ReflexV1012U(ac:197) ~[?:?]
        at rip.reflex.BB.accept(qj:150) ~[?:?]
        at rip.reflex.BB.ReflexV1012U(qj:193) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_144]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_144]
        at rip.reflex.MB.<init>(nk:177) ~[?:?]
        at rip.reflex.eB.ReflexV1012U(yj:83) ~[?:?]
        at rip.reflex.Reflex.valueOf(ge:531) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[PaperSpigot.jar:git-Paper-1104]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [PaperSpigot.jar:git-Paper-1104]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) [PaperSpigot.jar:git-Paper-1104]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_144]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_144]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[?:1.8.0_144]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[?:1.8.0_144]
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_144]
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_144]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[?:1.8.0_144]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_144]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_144]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_144]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_144]
        at rip.reflex.Fb.ReflexV1012U(ac:56) ~[?:?]
        at rip.reflex.Fb.valueOf(ac:41) ~[?:?]
        at rip.reflex.Fb.getBannedCountIn(ac:21) ~[?:?]
        at rip.reflex.Fb.ReflexV1012U(ac) ~[?:?]
        ... 15 more
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at sun.security.ssl.InputRecord.read(Unknown Source) ~[?:1.8.0_144]
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source) ~[?:1.8.0_144]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source) ~[?:1.8.0_144]
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_144]
        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source) ~[?:1.8.0_144]
        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source) ~[?:1.8.0_144]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source) ~[?:1.8.0_144]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source) ~[?:1.8.0_144]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source) ~[?:1.8.0_144]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source) ~[?:1.8.0_144]
        at rip.reflex.Fb.ReflexV1012U(ac:56) ~[?:?]
        at rip.reflex.Fb.valueOf(ac:41) ~[?:?]
        at rip.reflex.Fb.getBannedCountIn(ac:21) ~[?:?]
        at rip.reflex.Fb.ReflexV1012U(ac) ~[?:?]
        ... 15 more
Thanks

**Comment by CraftG** [comment]
I tested 10.1-1U, but the same.
I can run the 10.0-3U version perfectly on the server.

**Comment by Vktre** [comment]
The 3U is not realesed yet.

**Comment by Eyremba** [comment]
Please use https://p.reflex.rip/ for stacktraces.

**Comment by Vktre** [comment]
https://p.reflex.rip/CRPm.sql updated.

**Comment by MeGysssTaa** [comment]
Try disabling `general.use_ssl`.

**Comment by CraftG** [comment]
I closed the SSL, but it still have a mistake.
The error message is as follows:
https://p.reflex.rip/ZTep.sql

**Comment by CraftG** [comment]
I went to search for solutions:
Recently, a small program that implements cross-library resource retrieval based on different protocols is used to obtain the result page in the form of network fetching based on OpenURL, which encountered such errors:

The Server returned HTTP response code: 403 for URL: http://www... You can use the browser to access correctly

Because the server's security Settings do not accept Java programs as client access
Solution: set the User Agent

That is, after the url. OpenConnection () is added:
Connection. The setRequestProperty (" the user-agent ", "Mozilla / 4.0 (compatible; MSIE 5.0; Windows NT. DigExt) ");

**Comment by sinnlosername** [comment]
Does the 403 error still happen? Also, we know how to set an user-agent and we do. ^^

**Comment by Eyremba** [comment]
> Also, we know how to set an user-agent and we do. ^^

@sinnlosername He maybe knows that you are an austrian, so he maybe thought that you didn't know that. :P
