### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by YONONH** [MeGysssTaa/ReflexIssueTracker#152]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
console error

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
i see only console error.

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
don't have video.

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
`[Reflex] Unhandled exception occured in onPacketReceiving(PacketEvent) for Reflex
java.lang.IllegalStateException: Asynchronous entity add!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.World.addEntity(World.java:991) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.World.addEntity(World.java:987) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.EntityHuman.a(EntityHuman.java:630) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.EntityHuman.a(EntityHuman.java:620) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.EntityHuman.drop(EntityHuman.java:558) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.Container.b(Container.java:454) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.ContainerPlayer.b(ContainerPlayer.java:79) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.EntityPlayer.p(EntityPlayer.java:799) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.EntityPlayer.closeInventory(EntityPlayer.java:789) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:351) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
	at rip.reflex.Sc.accept(ef:163) ~[Reflex-10.1-2U%20(2).jar:?]
	at rip.reflex.OB.ReflexV1012U(vh:165) ~[Reflex-10.1-2U%20(2).jar:?]
	at rip.reflex.GC.accept(af:146) ~[Reflex-10.1-2U%20(2).jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_144]
	at rip.reflex.GC.onPacketReceiving(af:146) ~[Reflex-10.1-2U%20(2).jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib%20(3).jar:4.3.0]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib%20(3).jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib%20(3).jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib%20(3).jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib%20(3).jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib%20(3).jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:531) [ProtocolLib%20(3).jar:4.3.0]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:263) [ProtocolLib%20(3).jar:4.3.0]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at protocolsupport.protocol.core.timeout.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:40) [ProtocolSupport-1.8.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [spigot.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[11:08:37] [Netty Server IO #0/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInFlying@66b92254[
    x=0.0
    y=0.0
    z=0.0
    yaw=0.0
    pitch=0.0
    f=true
    hasPos=false
    hasLook=false
  ]`

**Comment by MeGysssTaa** [comment]
Stop ignoring the issue template. Fill it **FULLY**.

**Comment by YONONH** [comment]
sorry

**Comment by MeGysssTaa** [comment]
Still waiting for /reflex debug..

**Comment by YONONH** [comment]
i didn't see it since yesterday about 19.00 pm thanks for help.
