### ISSUE TITLE
Timings issue (at least reflex tells me)

### ISSUE THREAD

**Issue by geNAZt** [MeGysssTaa/ReflexIssueTracker#153]
[21:09:38] [Netty Epoll Server IO #1/WARN]: [Reflex] (!) | Reflex: Method checkKillAuraIn(async) execution took too long (lost 20 or more server ticks!): 2356 ms. If you see this message too often, your server seems to be heavily lagging (because of Reflex?), and it is advised that you send your /timings and /reflex timings at go.reflex.rip/bug
[21:09:38] [Netty Epoll Server IO #3/WARN]: [Reflex] (!) | Reflex: Method checkKillAuraIn(async) execution took too long (lost 20 or more server ticks!): 2350 ms. If you see this message too often, your server seems to be heavily lagging (because of Reflex?), and it is advised that you send your /timings and /reflex timings at go.reflex.rip/bug
[21:09:38] [Netty Epoll Server IO #6/WARN]: [Reflex] (!) | Reflex: Method checkKillAuraIn(async) execution took too long (lost 20 or more server ticks!): 2372 ms. If you see this message too often, your server seems to be heavily lagging (because of Reflex?), and it is advised that you send your /timings and /reflex timings at go.reflex.rip/bug
[21:09:38] [Netty Epoll Server IO #5/WARN]: [Reflex] (!) | Reflex: Method checkKillAuraIn(async) execution took too long (lost 20 or more server ticks!): 2397 ms. If you see this message too often, your server seems to be heavily lagging (because of Reflex?), and it is advised that you send your /timings and /reflex timings at go.reflex.rip/bug
[21:09:38] [Netty Epoll Server IO #4/WARN]: [Reflex] (!) | Reflex: Method checkKillAuraIn(async) execution took too long (lost 20 or more server ticks!): 2375 ms. If you see this message too often, your server seems to be heavily lagging (because of Reflex?), and it is advised that you send your /timings and /reflex timings at go.reflex.rip/bug
[21:09:38] [Netty Epoll Server IO #3/WARN]: [Reflex] (!) | Reflex: Method EU-5982143 execution took too long (lost 20 or more server ticks!): 2351 ms. If you see this message too often, your server seems to be heavily lagging (because of Reflex?), and it is advised that you send your /timings and /reflex timings at go.reflex.rip/bug
[21:09:38] [Netty Epoll Server IO #1/WARN]: [Reflex] (!) | Reflex: Method EU-5982143 execution took too long (lost 20 or more server ticks!): 2357 ms. If you see this message too often, your server seems to be heavily lagging (because of Reflex?), and it is advised that you send your /timings and /reflex timings at go.reflex.rip/bug
[21:09:38] [Netty Epoll Server IO #5/WARN]: [Reflex] (!) | Reflex: Method EU-5982143 execution took too long (lost 20 or more server ticks!): 2397 ms. If you see this message too often, your server seems to be heavily lagging (because of Reflex?), and it is advised that you send your /timings and /reflex timings at go.reflex.rip/bug
[21:09:38] [Netty Epoll Server IO #6/WARN]: [Reflex] (!) | Reflex: Method EU-5982143 execution took too long (lost 20 or more server ticks!): 2373 ms. If you see this message too often, your server seems to be heavily lagging (because of Reflex?), and it is advised that you send your /timings and /reflex timings at go.reflex.rip/bug
[21:09:38] [Netty Epoll Server IO #4/WARN]: [Reflex] (!) | Reflex: Method EU-5982143 execution took too long (lost 20 or more server ticks!): 2376 ms. If you see this message too often, your server seems to be heavily lagging (because of Reflex?), and it is advised that you send your /timings and /reflex timings at go.reflex.rip/bug

[21:09:38] [Head Conversion Thread - 0/WARN]: Exception in thread "Head Conversion Thread - 0" 
[21:09:38] [Head Conversion Thread - 0/WARN]: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at net.minecraft.server.v1_8_R3.TileEntitySkull$3.run(TileEntitySkull.java:160)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[21:09:38] [Head Conversion Thread - 0/WARN]: Caused by: java.lang.NullPointerException
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at net.minecraft.server.v1_8_R3.TileEntitySkull$1.load(TileEntitySkull.java:46)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at net.minecraft.server.v1_8_R3.TileEntitySkull$1.load(TileEntitySkull.java:1)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
[21:09:38] [Head Conversion Thread - 0/WARN]: 	... 8 more
[21:09:38] [Head Conversion Thread - 2/WARN]: Exception in thread "Head Conversion Thread - 2" 
[21:09:38] [Head Conversion Thread - 2/WARN]: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at net.minecraft.server.v1_8_R3.TileEntitySkull$3.run(TileEntitySkull.java:160)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[21:09:38] [Head Conversion Thread - 2/WARN]: Caused by: java.lang.NullPointerException
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at net.minecraft.server.v1_8_R3.TileEntitySkull$1.load(TileEntitySkull.java:46)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at net.minecraft.server.v1_8_R3.TileEntitySkull$1.load(TileEntitySkull.java:1)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
[21:09:38] [Head Conversion Thread - 2/WARN]: 	... 8 more
[21:09:38] [Head Conversion Thread - 4/WARN]: Exception in thread "Head Conversion Thread - 4" 
[21:09:38] [Head Conversion Thread - 4/WARN]: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at com.google.common.cache.LocalCache.get(LocalCache.java:3934)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at net.minecraft.server.v1_8_R3.TileEntitySkull$3.run(TileEntitySkull.java:160)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[21:09:38] [Head Conversion Thread - 4/WARN]: Caused by: java.lang.NullPointerException
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at net.minecraft.server.v1_8_R3.TileEntitySkull$1.load(TileEntitySkull.java:46)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at net.minecraft.server.v1_8_R3.TileEntitySkull$1.load(TileEntitySkull.java:1)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
[21:09:38] [Head Conversion Thread - 4/WARN]: 	... 8 more

This bug seems to cause players to randomly disconnect with a error

**Comment by MeGysssTaa** [comment]
The warnings can be ignored safely, they're just a part of debug we forgot to remove.
In case of performance issues there's Cloud Computings feature.

**Comment by geNAZt** [comment]
I doubt Cloud will be a solution here

**Comment by Janmm14** [comment]
what about the errors below the warnings

**Comment by MeGysssTaa** [comment]
That's not Reflex errors.
