### ISSUE TITLE
Kicking players in / after fight

### ISSUE THREAD

**Issue by geNAZt** [MeGysssTaa/ReflexIssueTracker#154]
We use a Bungeecord network. We get this in our Bungeecord Logs:

Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf$
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1401)
        at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707)
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108)
        at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98)
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:28)
        at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:10)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        ... 25 more

The User disconnects from the server and gets moved to a fallback.

Youtube Videos:

https://www.youtube.com/watch?v=KjLfVElDovY

https://www.youtube.com/watch?v=gatG3ZgNqrA

**Comment by Janmm14** [comment]
issue might be caused by sending packets while handling an outgoing packet hich is not getting cancelled

**Comment by geNAZt** [comment]
https://p.reflex.rip/t5cq

**Comment by EthanTG** [comment]
i know this is offtopic but

hi
