### ISSUE TITLE
1.9.4 - Could not load

### ISSUE THREAD

**Issue by Alpheos** [MeGysssTaa/ReflexIssueTracker#163]
[12:15:59] [Server thread/ERROR]: Could not load 'plugins/Reflex-10.2-1U.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: rip/reflex/ah
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[Spigot-v1_9_4.jar:git-Spigot-4af49dc-23da8b0]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[Spigot-v1_9_4.jar:git-Spigot-4af49dc-23da8b0]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [Spigot-v1_9_4.jar:git-Spigot-4af49dc-23da8b0]
	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:296) [Spigot-v1_9_4.jar:git-Spigot-4af49dc-23da8b0]
	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:200) [Spigot-v1_9_4.jar:git-Spigot-4af49dc-23da8b0]
	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532) [Spigot-v1_9_4.jar:git-Spigot-4af49dc-23da8b0]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoClassDefFoundError: rip/reflex/ah
	at rip.reflex.Reflex.<init>(en:135) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_144]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[Spigot-v1_9_4.jar:git-Spigot-4af49dc-23da8b0]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[Spigot-v1_9_4.jar:git-Spigot-4af49dc-23da8b0]
	... 6 more
Caused by: java.lang.ClassNotFoundException: rip.reflex.ah
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Spigot-v1_9_4.jar:git-Spigot-4af49dc-23da8b0]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Spigot-v1_9_4.jar:git-Spigot-4af49dc-23da8b0]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
	at rip.reflex.Reflex.<init>(en:135) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_144]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[Spigot-v1_9_4.jar:git-Spigot-4af49dc-23da8b0]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[Spigot-v1_9_4.jar:git-Spigot-4af49dc-23da8b0]
	... 6 more

**Comment by Janmm14** [comment]
Duplicate #157
