### ISSUE TITLE
Two console errors

### ISSUE THREAD

**Issue by Mxra** [MeGysssTaa/ReflexIssueTracker#171]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
Two console errors.

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
```
[22:40:22 INFO]: Homework issued server command: /reflex debug
[22:40:22 INFO]: Error while executing command (reflex)
[22:40:22 WARN]: java.lang.ClassCastException: org.bukkit.configuration.MemorySection cannot be cast to java.lang.CharSequence
[22:40:22 WARN]:        at rip.reflex.LA.ReflexV1022Urel(co:155)
[22:40:22 WARN]:        at rip.reflex.Xb.ReflexV1022Urel(qd:29)
[22:40:22 WARN]:        at rip.reflex.xB.ReflexV1022Urel(qd:58)
[22:40:22 WARN]:        at rip.reflex.y.run(qa:98)
[22:40:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:40:22 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:40:22 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
```
[22:37:56 INFO]: (Reflex/INFO) | Homework joined with "vanilla"
[22:38:03 INFO]: (Reflex/WARN) | An error occurred executing Reflex runnable with id 'r#@7_f/+                                                        | 840A^8|'
[22:38:03 WARN]: java.lang.NullPointerException
[22:38:03 WARN]:        at rip.reflex.FC.ReflexV1022Urel(mf:59)
[22:38:03 WARN]:        at rip.reflex.y.run(qa:98)
[22:38:03 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[22:38:03 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[22:38:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[22:38:03 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[22:38:03 WARN]:        at java.lang.Thread.run(Unknown Source)
```

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**

**Comment by Eyremba** [comment]
@Mxra For the future, please use https://p.reflex.rip/ (Our own text pasting service) for Reflex Stacktraces, as this allows us faster access and handling of them.
