### ISSUE TITLE
stopTiming called async (related indirectly)

### ISSUE THREAD

**Issue by MeGysssTaa** [MeGysssTaa/ReflexIssueTracker#193]
***FIXING THE ERROR MAKES THE CAUSE ESCALATE TO SERVER CRASHES***
```
[14:27:42] [Netty Epoll Server IO #1/ERROR]: stopTiming called async for world - chunkLoad - Entities
[14:27:42] [Netty Epoll Server IO #1/WARN]: java.lang.Throwable
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:424)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:132)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:114)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:144)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:90)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.block.CraftBlock.getRelative(CraftBlock.java:179)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.block.CraftBlock.getRelative(CraftBlock.java:187)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.block.CraftBlock.getRelative(CraftBlock.java:183)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.util.BlockIterator.scan(BlockIterator.java:346)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.util.BlockIterator.hasNext(BlockIterator.java:286)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.getLineOfSight(CraftLivingEntity.java:163)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftLivingEntity.getTargetBlock(CraftLivingEntity.java:197)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at rip.reflex.aa.a(aa.java:19)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at rip.reflex.a6.a(a6.java:71)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at rip.reflex.b.lambda$onPacketReceiving$0(b.java:3)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at java.util.ArrayList.forEach(ArrayList.java:1255)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at rip.reflex.b.onPacketReceiving(b.java:1)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:610)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:577)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:323)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:288)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:541)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:249)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:149)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$4.channelRead(ChannelInjector.java:273)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollInReady(EpollSocketChannel.java:722)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:326)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[14:27:42] [Netty Epoll Server IO #1/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```
note 020

**Comment by UnioDex** [comment]
It happens to me too lately:
https://pastebin.com/r3hfVFXf

**Comment by UnioDex** [comment]
Can you explain what this Exception says? Why is that happening and can i fix it ?

**Comment by MeGysssTaa** [comment]
Sadly, nothing can be done with it.

**Comment by MatrixTunnel** [comment]
Just got this error again while messing around on my test server. The first few errors that happen are different from the rest which should help find the cause of the issue https://p.reflex.rip/Q89s.md
(`java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns`)

**Comment by FinalPacket** [comment]
Could it be ProtocolLib's problem with the way it handles the packets? @MeGysssTaa 
Maybe it isn't Reflex's problem since it happens on all versions.

**Comment by UnioDex** [comment]
It is still happening with the latest version of Reflex.

https://pastebin.com/Spsn1n7B

**Comment by MatrixTunnel** [comment]
I talked to @MeGysssTaa about this issue in Discord. He thinks it will be fixed in the next version *crosses fingers* but for now you can just disable timings and it shouldn’t happen (I’ve been running my server for weeks now with no issues)
