### ISSUE TITLE
java.lang.ArithmeticException: integer overflow

### ISSUE THREAD

**Issue by LeimonDust** [MeGysssTaa/ReflexIssueTracker#228]
[22:53:51] [Server thread/ERROR]: [Reflex] Unhandled exception occured in onPacketSending(PacketEvent) for Reflex
java.lang.ArithmeticException: integer overflow
	at java.lang.Math.toIntExact(Math.java:1011) ~[?:1.8.0_151]
	at rip.reflex.LB.ReflexV1022Urel(hf:73) ~[Reflex-10.4-1U.jar:?]
	at rip.reflex.LB.ReflexV1022Urel(hf:50) ~[Reflex-10.4-1U.jar:?]
	at rip.reflex.vC.ReflexV1022Urel(fh:76) ~[Reflex-10.4-1U.jar:?]
	at rip.reflex.GA.saveData(wh:71) ~[Reflex-10.4-1U.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1255) ~[?:1.8.0_151]
	at rip.reflex.GA.onPacketSending(wh:71) ~[Reflex-10.4-1U.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:386) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector.access$500(ChannelInjector.java:77) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.handleScheduled(ChannelInjector.java:352) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelInjector$5.onMessageScheduled(ChannelInjector.java:320) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) [ProtocolLib.jar:4.3.0]
	at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) [ProtocolLib.jar:4.3.0]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:199) [patched_1.12.2.jar:git-Paper-fc911a20]
	at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:147) [patched_1.12.2.jar:git-Paper-fc911a20]
	at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1183) [patched_1.12.2.jar:git-Paper-fc911a20]
	at net.minecraft.server.v1_12_R1.PlayerConnection.e(PlayerConnection.java:198) [patched_1.12.2.jar:git-Paper-fc911a20]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:254) [patched_1.12.2.jar:git-Paper-fc911a20]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [patched_1.12.2.jar:git-Paper-fc911a20]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:940) [patched_1.12.2.jar:git-Paper-fc911a20]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-fc911a20]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-fc911a20]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-fc911a20]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
[22:53:51] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_12_R1.PacketPlayOutKeepAlive@8eca826[
    a=2240955575
  ]

**Comment by MeGysssTaa** [comment]
Extremely outdated Reflex version...
