### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by minhthanh920** [MeGysssTaa/ReflexIssueTracker#291]
[05:38:22 ERROR]: [Reflex] Unhandled exception occured in onPacketReceiving(PacketEvent) for Reflex
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.ConcurrentHashMap.put(Unknown Source) ~[?:1.8.0_181]
        at rip.reflex.Od.onPacketReceiving(yf:124) ~[Reflex-10.7-2.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:505) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24) [ProtocolSupport%201.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39) [ProtocolSupport%201.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
[05:38:22 INFO]: is leader = false
[05:38:22 ERROR]: Parameters:
  net.minecraft.server.v1_12_R1.PacketPlayInSettings@6bf9c6e3[
    a=vi_vn
    b=16
    c=FULL
    d=true
    e=127
    f=Right
  ]

[05:38:22 INFO]: minhthanh920[/127.0.0.1:37190] logged in with entity id 307 at ([Lobby]-1026.5727121016894, 70.0, 339.7799830997413)
[05:38:22 INFO]: (Reflex/INFO) | minhthanh920's client brand is "liteloader"
[05:38:22 INFO]: (Reflex/INFO) | minhthanh920 joined with MC 1.12x (vi_vn)
[05:38:24 INFO]: minhthanh920 issued server command: /we cui
[05:38:27 INFO]: [AuthMe] minhthanh920 used the wrong password
[05:38:27 INFO]: minhthanh920 lost connection: ºcSai m?t kh?u!
[05:38:27 WARN]: handleDisconnection() called twice
[05:38:30 INFO]: UUID of player minhthanh920 is 206d439e-974a-3819-bffe-82f4d8b7adfd
[05:38:30 INFO]: is leader = false
[05:38:30 INFO]: minhthanh920[/127.0.0.1:37192] logged in with entity id 576 at ([Lobby]-1026.5727121016894, 70.0, 339.7799830997413)
[05:38:30 ERROR]: [Reflex] Unhandled exception occured in onPacketReceiving(PacketEvent) for Reflex
java.lang.NullPointerException: null
        at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source) ~[?:1.8.0_181]
        at java.util.concurrent.ConcurrentHashMap.put(Unknown Source) ~[?:1.8.0_181]
        at rip.reflex.Od.onPacketReceiving(yf:124) ~[Reflex-10.7-2.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:590) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketRecieving(PacketFilterManager.java:557) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetReceived(ProtocolInjector.java:352) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketReceiving(ProtocolInjector.java:317) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:505) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248) [ProtocolLib.jar:4.4.0-SNAPSHOT-b403]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at protocolsupport.protocol.pipeline.common.RawPacketDataCaptureReceive.channelRead(RawPacketDataCaptureReceive.java:24) [ProtocolSupport%201.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at protocolsupport.protocol.pipeline.common.SimpleReadTimeoutHandler.channelRead(SimpleReadTimeoutHandler.java:39) [ProtocolSupport%201.12.2.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
[05:38:31 ERROR]: Parameters:
  net.minecraft.server.v1_12_R1.PacketPlayInSettings@2b267e9[
    a=vi_vn
    b=16
    c=FULL
    d=true
    e=127
    f=Right
  ]

**Comment by TheWranger** [comment]
Getting this as well, whenever a player joins.

**Comment by NaNaShiSan1** [comment]
Or ... using templates?

**Comment by TheWranger** [comment]
I'll make a new issue regarding this issue that follows the proper template, since this user hasn't done so.
