### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Lorexdx** [MeGysssTaa/ReflexIssueTracker#390]
(Reflex/INFO) | Choosen servers: sync: EU, cloud: EU
[01:08:47 INFO]: (Reflex/WARN) | Disabling Reflex due to piracy. If you believe that this is an issue, make sure to open a report at go.reflex.rip/bug
[01:08:47 WARN]: Exception in thread "pool-3-thread-2"
[01:08:47 WARN]: org.apache.commons.lang.UnhandledException: Plugin Reflex v11.3-5-27732ae generated an exception while executing task 4
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: rip.reflex.aN: ?
Caused by: rip.reflex.aN: d

>

**Comment by MeGysssTaa** [comment]
Hi! Please message me in Discord mentioning this issue and your SpigotMC profile link: DarksideSkid#1491
