### ISSUE TITLE
Reflection IllegalAccessException

### ISSUE THREAD

**Issue by MeGysssTaa** [MeGysssTaa/ReflexIssueTracker#47]
[22:06:39 INFO]: [Reflex] Enabling Reflex v10.0-2U
[22:06:39 ERROR]: Error occurred while enabling Reflex v10.0-2U (Is it up to date?)
java.lang.IllegalAccessException: Class java.lang.invoke.LambdaForm$NamedFunction can not access a member of class rip.reflex.Reflex with modifiers "static"
at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:101) ~[?:1.8.0_25]
at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:295) ~[?:1.8.0_25]
at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:287) ~[?:1.8.0_25]
at java.lang.reflect.Method.invoke(Method.java:476) ~[?:1.8.0_25]
at rip.reflex.Reflex.onEnable(Reflex.java:103) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-e4d4710-e1ebe52]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_25]

**Comment by sinnlosername** [comment]
Fixed
