### ISSUE TITLE
MySQL issue

### ISSUE THREAD

**Issue by MeGysssTaa** [MeGysssTaa/ReflexIssueTracker#50]
```
[16:56:30] [Craft Scheduler Thread - 5/WARN]: Exception in thread "Craft Scheduler Thread - 5"
[16:56:30] [Craft Scheduler Thread - 5/WARN]: org.apache.commons.lang.UnhandledException: Plugin Reflex v10.0-2U generated an exception while executing task 28
   at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
   at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Error while downloading
   at rip.reflex.a_.a(a_.java:10)
   at rip.reflex.a1.b(a1.java:76)
   at rip.reflex.a1.a(a1.java:23)
   at rip.reflex.Q.<init>(Q.java:22)
   at rip.reflex.Reflex.i(Reflex.java:27)
   at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
   at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
   ... 4 more
Caused by: rip.reflex.bw: MySQL / Error while executing prepared query
   at rip.reflex.bF.a(bF.java:8)
   at rip.reflex.b7.a(b7.java:8)
   at rip.reflex.a_.a(a_.java:41)
   at rip.reflex.aV.a(aV.java:9)
   at rip.reflex.a_.c(a_.java:72)
   at rip.reflex.a_.a(a_.java:13)
   ... 10 more
Caused by: java.sql.SQLException: No value specified for parameter 2
   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:987)
   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:982)
   at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:927)
   at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2558)
   at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2534)
   at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2381)
   at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
   at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
   at rip.reflex.bF.a(bF.java:17)
   ... 15 more
```

**Comment by sinnlosername** [comment]
Fixed.
