### ISSUE TITLE
Reflex is throwing an exception on startup

### ISSUE THREAD

**Issue by Paulomart** [MeGysssTaa/ReflexIssueTracker#56]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
bug

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
Command does nothing

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
```
[20:37:52] [Server thread/INFO]: Starting minecraft server version 1.8.8
[20:37:52] [Server thread/INFO]: Loading properties
[20:37:52] [Server thread/INFO]: Default game type: SURVIVAL
[20:37:52] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[20:37:52] [Server thread/INFO]: Debug logging is disabled
[20:37:52] [Server thread/INFO]: Server Ping Player Sample Count: 12
[20:37:52] [Server thread/INFO]: Using 4 threads for Netty based IO
[20:37:52] [Server thread/INFO]: Generating keypair
[20:37:52] [Server thread/INFO]: Starting Minecraft server on *:25577
[20:37:52] [Server thread/INFO]: Using default channel type
[20:37:53] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[20:37:53] [Server thread/INFO]: net.madgamble.core.injector.security.ASM is loaded by sun.misc.Launcher$AppClassLoader@42a57993
[20:37:53] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v1.0.5-1_12pre2
[20:37:53] [Server thread/INFO]: [ViaVersion] ViaVersion 1.0.5-1_12pre2 is now loaded, injecting!
[20:37:53] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.2.1
[20:37:54] [Server thread/INFO]: [Reflex] Loading Reflex v9.1
[20:37:54] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.2.1
[20:37:54] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[20:37:54] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[20:37:54] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[20:37:54] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[20:37:54] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[20:37:54] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[20:37:54] [Server thread/INFO]: Preparing level "world"
[20:37:54] [Server thread/INFO]: -------- World Settings For [world] --------
[20:37:54] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[20:37:54] [Server thread/INFO]: Max Entity Collisions: 8
[20:37:54] [Server thread/INFO]: Experience Merge Radius: 3.0
[20:37:54] [Server thread/INFO]: Chunks to Grow per Tick: 650
[20:37:54] [Server thread/INFO]: Clear tick list: false
[20:37:54] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[20:37:54] [Server thread/INFO]: Item Merge Radius: 2.5
[20:37:54] [Server thread/INFO]: Item Despawn Rate: 6000
[20:37:54] [Server thread/INFO]: View Distance: 10
[20:37:54] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[20:37:54] [Server thread/INFO]: Arrow Despawn Rate: 1200
[20:37:54] [Server thread/INFO]: Random Lighting Updates: false
[20:37:54] [Server thread/INFO]: Structure Info Saving: true
[20:37:54] [Server thread/INFO]: Mob Spawn Range: 4
[20:37:54] [Server thread/INFO]: Anti X-Ray: true
[20:37:54] [Server thread/INFO]: 	Engine Mode: 1
[20:37:54] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[20:37:54] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[20:37:54] [Server thread/INFO]: Cactus Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Cane Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Melon Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Sapling Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Wheat Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[20:37:54] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[20:37:54] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[20:37:54] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[20:37:54] [Server thread/INFO]: Max TNT Explosions: 100
[20:37:54] [Server thread/INFO]: Sending up to 10 chunks per packet
[20:37:54] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[20:37:54] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[20:37:54] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[20:37:54] [Server thread/INFO]: Max Entity Collisions: 8
[20:37:54] [Server thread/INFO]: Experience Merge Radius: 3.0
[20:37:54] [Server thread/INFO]: Chunks to Grow per Tick: 650
[20:37:54] [Server thread/INFO]: Clear tick list: false
[20:37:54] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[20:37:54] [Server thread/INFO]: Item Merge Radius: 2.5
[20:37:54] [Server thread/INFO]: Item Despawn Rate: 6000
[20:37:54] [Server thread/INFO]: View Distance: 10
[20:37:54] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[20:37:54] [Server thread/INFO]: Arrow Despawn Rate: 1200
[20:37:54] [Server thread/INFO]: Random Lighting Updates: false
[20:37:54] [Server thread/INFO]: Structure Info Saving: true
[20:37:54] [Server thread/INFO]: Mob Spawn Range: 4
[20:37:54] [Server thread/INFO]: Anti X-Ray: true
[20:37:54] [Server thread/INFO]: 	Engine Mode: 1
[20:37:54] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[20:37:54] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[20:37:54] [Server thread/INFO]: Cactus Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Cane Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Melon Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Sapling Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Wheat Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[20:37:54] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[20:37:54] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[20:37:54] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[20:37:54] [Server thread/INFO]: Max TNT Explosions: 100
[20:37:54] [Server thread/INFO]: Sending up to 10 chunks per packet
[20:37:54] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[20:37:54] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[20:37:54] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[20:37:54] [Server thread/INFO]: Max Entity Collisions: 8
[20:37:54] [Server thread/INFO]: Experience Merge Radius: 3.0
[20:37:54] [Server thread/INFO]: Chunks to Grow per Tick: 650
[20:37:54] [Server thread/INFO]: Clear tick list: false
[20:37:54] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[20:37:54] [Server thread/INFO]: Item Merge Radius: 2.5
[20:37:54] [Server thread/INFO]: Item Despawn Rate: 6000
[20:37:54] [Server thread/INFO]: View Distance: 10
[20:37:54] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[20:37:54] [Server thread/INFO]: Arrow Despawn Rate: 1200
[20:37:54] [Server thread/INFO]: Random Lighting Updates: false
[20:37:54] [Server thread/INFO]: Structure Info Saving: true
[20:37:54] [Server thread/INFO]: Mob Spawn Range: 4
[20:37:54] [Server thread/INFO]: Anti X-Ray: true
[20:37:54] [Server thread/INFO]: 	Engine Mode: 1
[20:37:54] [Server thread/INFO]: 	Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[20:37:54] [Server thread/INFO]: 	Replace Blocks: [1, 5]
[20:37:54] [Server thread/INFO]: Cactus Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Cane Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Melon Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Sapling Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Wheat Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[20:37:54] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[20:37:54] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[20:37:54] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[20:37:54] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[20:37:54] [Server thread/INFO]: Max TNT Explosions: 100
[20:37:54] [Server thread/INFO]: Sending up to 10 chunks per packet
[20:37:54] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[20:37:54] [Server thread/INFO]: Preparing start region for level 0 (Seed: -8069080247677079077)
[20:37:54] [Server thread/INFO]: Preparing start region for level 1 (Seed: -8069080247677079077)
[20:37:55] [Server thread/INFO]: Preparing start region for level 2 (Seed: -8069080247677079077)
[20:37:55] [Server thread/INFO]: [ViaVersion] Enabling ViaVersion v1.0.5-1_12pre2
[20:37:55] [Server thread/INFO]: [Reflex] Enabling Reflex v9.1
[20:37:55] [Server thread/INFO]: Reflex » Found ProtocolLib v4.2.1, everything's correct
[20:37:55] [Server thread/INFO]: Reflex » (Reflex) Beginning enable...
[20:37:55] [Server thread/WARN]: [Reflex] Default system encoding may have misread config.yml from plugin jar
[20:37:55] [Server thread/INFO]: Reflex » Running Reflex 9.1 (~DarksideCode & sinnlosername)
[20:37:55] [Server thread/INFO]: Reflex » Running Reflex thread heartbeat...
[20:37:55] [Server thread/INFO]: java.io.IOException
[20:37:55] [Server thread/WARN]: *** CANT CHECK FOR PIRACY ***
[20:37:55] [Server thread/WARN]: Please purchase Reflex at www.spigotmc.org/resources/21122
[20:37:55] [Server thread/WARN]: If this is a false positive, please report this isuse!
[20:37:55] [Server thread/WARN]: Send this to developers: SU9FeGNlcHRpb247U2VydmVyIHJldHVybmVkIEhUVFAgcmVzcG9uc2UgY29kZTogNTAwIGZvciBVUkw6IGh0dHA6Ly9yZWZsZXgucmlwL3JlZmxleC9jaC5waHA/YT1kNDFkOGNkOThmMDBiMjA0ZTk4MDA5OThlY2Y4NDI3ZSZiPTAzMzU4MjI1IHwgSkRLIDEuOC4wXzEyMQ==
[20:37:55] [Server thread/INFO]: [Reflex] Disabling Reflex v9.1
[20:37:55] [Server thread/ERROR]: Error occurred while enabling Reflex v9.1 (Is it up to date?)
java.security.AccessControlException: Access violation: System.exit(0)
	at net.madgamble.core.injector.security.CoreSecurityManager.checkExit(CoreSecurityManager.java:58) ~[launchwrapper-injectors-bSNAPSHOT.jar:SNAPSHOT]
	at java.lang.Runtime.exit(Unknown Source) ~[?:1.8.0_121]
	at java.lang.System.exit(Unknown Source) ~[?:1.8.0_121]
	at rip.reflex.c2.a(c2.java:36) ~[?:?]
	at rip.reflex.bt.println(bt.java:17) ~[?:?]
	at rip.reflex.c2.d(c2.java:13) ~[?:?]
	at rip.reflex.main.i.a(i.java:77) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at rip.reflex.main.ReflexMain.onEnable(ReflexMain.java:7) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot-1.8.8.jar:git-Spigot-21fe707-e1ebe52]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[20:37:55] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:37:55] [Server thread/INFO]: Done (1,834s)! For help, type "help" or "?"
[20:37:56] [Server thread/INFO]: [ViaVersion] ViaVersion detected server version: 1.8.x(47)
[20:37:56] [Server thread/WARN]: [ViaVersion] You are running a newer version than is released!
[20:41:17] [Server thread/INFO]: Unknown command. Type "/help" for help.

```

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**

**Comment by sinnlosername** [comment]
Do you run your minecraft server on a vps/root server? If not, where do you host it?
Do you use any custom security managers?

**Comment by Paulomart** [comment]
We host it on our own root servers. Yes are are using our own security manager: You can see that Reflex is trying to shutdown the server, the security manager is preventing this and other things (not interfering with Reflex.)

**Comment by sinnlosername** [comment]
You are using an old version of reflex. It seems like this is already removed in the latest version.

**Comment by Paulomart** [comment]
Oh I see, we will update, thank you.
