### ISSUE TITLE
MySql error

### ISSUE THREAD

**Issue by fdsjl** [MeGysssTaa/ReflexIssueTracker#68]
**Issue type (console error/false positive/bypass/other):**
Console error
**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**

[03:07:38 WARN]: Exception in thread "Craft Scheduler Thread - 2"
[03:07:38 WARN]: org.apache.commons.lang.UnhandledException: Plugin Reflex v10.0-3U generated an exception while executing task 33
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Error while downloading
        at rip.reflex.IB.ReflexV103U(hc:64)
        at rip.reflex.xB.log(mc:171)
        at rip.reflex.xB.ReflexV103U(mc:211)
        at rip.reflex.Vb.<init>(gh:95)
        at rip.reflex.Reflex.ReflexV103U(hd:152)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
Caused by: rip.reflex.eC: MySQL / Error while executing prepared query
        at rip.reflex.Kc.ReflexV103U(do:107)
        at rip.reflex.Kd.saveData(yc:209)
        at rip.reflex.IB.ReflexV103U(hc:108)
        at rip.reflex.HA.ReflexV103U(mc:143)
        at rip.reflex.IB.isConnected0(hc:138)
        at rip.reflex.IB.ReflexV103U(hc:51)
        ... 9 more
Caused by: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (7049521 > 1048576). You can change this value on the server by setting the max_allowed_packet' variable.
        at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3275)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1967)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310)
        at rip.reflex.Kc.ReflexV103U(do:174)
        ... 14 more

I use many other plugins that require databases and they work fine.

**Comment by MeGysssTaa** [comment]
Caused by: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (7049521 > 1048576). **You can change this value on the server by setting the max_allowed_packet' variable.**

That's what you should do. Not our bug.
