### ISSUE TITLE
Downloading dataset file

### ISSUE THREAD

**Issue by mechoriet** [MeGysssTaa/ReflexIssueTracker#74]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
console error downloading neural file(i think)
happened after enabling mysql

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
N/A

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**
N/A

**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**
N/A

```java
23.06 18:00:12 [Server] WARN Plugin Reflex v10.0-3U generated an exception while executing task 4
23.06 18:00:12 [Server] INFO java.lang.RuntimeException: Error while downloading
23.06 18:00:12 [Server] INFO at rip.reflex.IB.ReflexV103U(hc:64) ~[?:?]
23.06 18:00:12 [Server] INFO at rip.reflex.xB.log(mc:171) ~[?:?]
23.06 18:00:12 [Server] INFO at rip.reflex.xB.ReflexV103U(mc:211) ~[?:?]
23.06 18:00:12 [Server] INFO at rip.reflex.Vb.<init>(gh:95) ~[?:?]
23.06 18:00:12 [Server] INFO at rip.reflex.Reflex.ReflexV103U(hd:152) ~[?:?]
23.06 18:00:12 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigotlatest.jar:git-Spigot-b78586d-7638276]
23.06 18:00:12 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigotlatest.jar:git-Spigot-b78586d-7638276]
23.06 18:00:12 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
23.06 18:00:12 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
23.06 18:00:12 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
````

**Comment by MeGysssTaa** [comment]
Not the full stacktrace. The "caused by" part seems missing. Please send the full error or the entire log on server startup.
