### ISSUE TITLE
killaura error

### ISSUE THREAD

**Issue by yuitaka** [MeGysssTaa/ReflexIssueTracker#87]
**Issue type**
Bug.

**/reflex debug output**
https://p.reflex.rip/AdTN

**Evidence**
https://www.youtube.com/watch?v=W_LXfVx1yU0&feature=youtu.be

**Additional information**
Hitting an entity causes client to get disconnected.
Logs: [log.zip](https://github.com/MeGysssTaa/ReflexIssueTracker/files/1132698/log.zip)

**Comment by MeGysssTaa** [comment]
What is issue template for? I guess not for erasing it. Issue is invalid until all of the neccessary info from issue template is providen.

**Comment by yuitaka** [comment]
If you hit an NPC with Killaura you will not be BAN and you are vomiting an error

**Comment by MeGysssTaa** [comment]
[This is what your issue should look like.](https://sc.reflex.rip/dlHUBQ.png)

**Comment by yuitaka** [comment]
## Reflex Bug Report
**Issue type (console error/false positive/bypass/other):**
error

**Do /reflex debug, and paste here the link you've got. Keep empty if on test server:**
[Reflex] (!) | Reflex: An error occurred executing Reflex runnable with id 'check0-thread | ^MV:%c\'

java.lang.NullPointerException
at rip.reflex.OC.getBanCount(co:165)
at rip.reflex.Reflex.ReflexV103U(hd:524)
at rip.reflex.Vc.ReflexV103U(tg:472)
at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
at java.util.stream.ReferencePipeline.forEach(Unknown Source)
at rip.reflex.Vc.ReflexV103U(tg:284)
at rip.reflex.B.run(j:133)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
at java.lang.Thread.run(Unknown Source)

**A video proving the bypass/false positive if reporting a bypass/false positive, a link to your server log if reporting a console error, or a link to your Reflex log if reporting a bypass/false positive:**


**Additional information (i.e. how to reproduce the issue you are experiencing etc.):**

**Comment by Eyremba** [comment]
@yuitaka, on this stacktrace, where is the "caused by"? ;)

**Comment by yuitaka** [comment]
https://www.youtube.com/watch?v=W_LXfVx1yU0&feature=youtu.be

**Comment by MeGysssTaa** [comment]
@yuitaka please type /reflex debug in-game. It will give you a link. Send this link here.

**Comment by yuitaka** [comment]
https://p.reflex.rip/AdTN

**Comment by MeGysssTaa** [comment]
Please do the following:
- Go to your **server.properties** file and set there **debug** to **true**.
- Go to your **spigot.yml** file and set there **debug** to **true**.
- Restart your server (**/restart**).
- Reproduce this issue again, and send here your logs.

**Comment by yuitaka** [comment]
https://p.reflex.rip/PZHp

**Comment by yuitaka** [comment]
[Reflex] (!) | Reflex: An error occurred executing Reflex runnable with id 'check0-thread  | pLTx5cl'
java.lang.NullPointerException
       at rip.reflex.OC.getBanCount(co:165)
       at rip.reflex.Reflex.ReflexV103U(hd:524)
       at rip.reflex.Vc.ReflexV103U(tg:472)
       at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
       at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
       at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
       at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
       at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
       at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
       at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
       at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
       at java.util.stream.ReferencePipeline.forEach(Unknown Source)
       at rip.reflex.Vc.ReflexV103U(tg:284)
       at rip.reflex.B.run(j:133)
       at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
       at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
       at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
       at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
       at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
       at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
       at java.lang.Thread.run(Unknown Source)
yuitaka lost connection: Disconnected

**Comment by MeGysssTaa** [comment]
Please stop sending useless console errors again and again. Re-read my previous message carefully, and do everything step by step. We need whole logs, with **debug** option enabled both in **server.properties** and **spigot.yml**.

**Comment by yuitaka** [comment]
Both I made debug true, but where are the logs?

**Comment by MeGysssTaa** [comment]
/your_server_folder/logs/latest.log

**Comment by yuitaka** [comment]
https://p.reflex.rip/

**Comment by yuitaka** [comment]
[log.zip](https://github.com/MeGysssTaa/ReflexIssueTracker/files/1132698/log.zip)

**Comment by yuitaka** [comment]
There is one thing I understand now. It works normally if you do it in the previous version. It is only the latest version that does not work properly. I do not know about plugins, but is not it related to API? Also, if you turn earlier and turn it on earlier version, you will cause negative and positive nature. Therefore it would be greatly appreciated if you improve that setting or increase the settings such as execution if you hit a certain number

**Comment by MeGysssTaa** [comment]
Try to remove all plugins you have and try on a clean server, with ProtocolLib only.

**Comment by yuitaka** [comment]
I tried to execute it, but I will not even kick it this time. Just issue errors at the console

**Comment by MeGysssTaa** [comment]
So the problem is in incompatibility with some of plugins you use - it isn't Reflex's fault.
You shall try to install plugins one by one and check which of them is incompatible.

**Comment by yuitaka** [comment]
What? I said the results on Server with ProtocolLib and Reflex alone

**Comment by MeGysssTaa** [comment]
Disconnect issue seems to be caused by one or more plugin(s) you use, it isn't Reflex's fault.
If you wanna fix this, try installing plugins you have one by one and check which of them causes this problem.
